### ISSUE TITLE
Other useful sites should be a list

### ISSUE THREAD

**Issue by i1v** [wwhtrbbtt/TrackMe#12]
https://github.com/wwhtrbbtt/TrackMe/blob/fb5f6dbfff5027105e8421eeafa2f4828df5ddf3/static/index.html#L212-L291

https://tls.peet.ws

like this:

~~~html
<ul>
   <li>
      <a href="hello">hello</a>
   </li>
   <li>
      <a href="world">world</a>
   </li>
</ul>
~~~

**Comment by wwhtrbbtt** [comment]
Hey, yes, you are right. Do you want to fork it and make a pull request?

**Comment by i1v** [comment]
https://github.com/wwhtrbbtt/TrackMe/pull/13

**Comment by i1v** [comment]
how long does it take to go live?
