### ISSUE TITLE
eth0: No such device exists (SIOCGIFHWADDR: No such device)

### ISSUE THREAD

**Issue by atyachin** [wwhtrbbtt/TrackMe#17]
When running the server on an EC2 machine, the following error occurs:
`eth0: No such device exists (SIOCGIFHWADDR: No such device)`

Reason is that in tcp.go file the device name is hardcoded to "eth0", whereas the default device name on an AWS EC2 machine is different (e.g. "ens5").

Suggested fix: add the device name to config.json.
(of course re-compilation with correct device name is also an option...)

Thanks!

**Comment by wwhtrbbtt** [comment]
This has been implemented by a recent pull request! Thanks for the patience :)
