### ISSUE TITLE
Expired certificate for tls.peet.ws

### ISSUE THREAD

**Issue by zebrapurring** [wwhtrbbtt/TrackMe#23]
Seems like the certificate for https://tls.peet.ws/ expired a couple of days ago:

```
notBefore=May 30 23:14:55 2024 GMT
notAfter=Aug 28 23:14:54 2024 GMT
```

**Comment by wwhtrbbtt** [comment]
Hey, you're right, I forgot to renew it.
I have to renew it manually, because my setup is a bit scuffed, as I'm not able to use nginx because of the low-level hacks it's doing.
Renewed it now!

**Comment by zebrapurring** [comment]
Amazing, thanks for the quick response!

**Comment by eidorb** [comment]
Heads up!

```console
$ echo | openssl s_client -connect tls.peet.ws:443 -servername tls.peet.ws 2>/dev/null | openssl x509 -noout -enddate
notAfter=Jan 25 18:17:44 2026 GMT
$ date -u
Sun 25 Jan 2026 23:37:38 UTC
```
