### ISSUE TITLE
Not working correctly on firefox

### ISSUE THREAD

**Issue by 89z** [wwhtrbbtt/TrackMe#5]
half the time I am getting a blank page. If I inspect source - I can see some stuff - so I am not sure what is going on:

https://tls.peet.ws

**Comment by wwhtrbbtt** [comment]
Are you using firefox?

**Comment by 89z** [comment]
yes

**Comment by wwhtrbbtt** [comment]
The whole server implementation is pretty rough, to say the least, and firefox is less forgiving than chromium based browsers.
The biggest things are that a) connections are immediately closed, and that b) the responses should be split up in multiple DATA frames, because they are too big for one. Chrome doesn't seem to care, firefox does.
Splitting up the answer in multiple frames isn't a hard fix, I will implement this in the next days.
Reusing connections is more work

The API endpoints work better (kinda) - https://tls.peet.ws/api/all, /api/clean, /api/tls

**Comment by 89z** [comment]
> connections are immediately closed

I am probably dumb here, but I don't see why this matters at all. The close connection comes at the VERY end of the conversation, even after the HTTP body. The TLS is negotiated way before that, so even if the client aggressively disconnects, the TLS info should be available. Again you probably know more than me about this.

**Comment by wwhtrbbtt** [comment]
I am not sure if this is a problem, but it could be one.
A client could send multiple http/2 HEADER frames over the same TCP connection, but the server terminates the connection after the first HEADER frame is received, and without answering to other possible requests on the same connection.
Again, this might not be the problem at all, I am not sure, but it could be because firefox seems
<img width="1325" alt="Bildschirmfoto 2022-09-12 um 20 14 37" src="https://user-images.githubusercontent.com/64318024/189726528-7416ab4c-31ba-47f1-ad12-2bff9a57346b.png">
 to be behaving very weird, not even showing some requests in the dev console.

**Comment by 89z** [comment]
yeah, I got the same four requests, which looks normal to me. Are some requests missing? I check the JavaScript console, and didn't see any errors

**Comment by 89z** [comment]
I think the problem is the script itself. Its below. From what I can tell, the below script doesnt actually do anything, it only defines functions.

~~~js
const insert = data => {
   console.log(data)

   d = document

   d.getElementById('ja3-hash').innerText = data.tls.ja3_hash;
   d.getElementById('ja3').innerText = data.tls.ja3;

   d.getElementById('akamai-hash').innerText = data.http2.akamai_fingerprint_hash;
   d.getElementById('akamai').innerText = data.http2.akamai_fingerprint;

   d.getElementById("tls-version").innerText = data.tls.version;
   d.getElementById("http-version").innerText = (data.http_version == "h2" ? "HTTP/2" : "HTTP/1.1");
   d.getElementById("tls-versions").innerText = data.tls.versions.join(", ");
   d.getElementById("http-versions").innerText = data.tls.protocols.join(", ");
   if (data.http_version == "h2") {
       d.getElementById("h2-frames").innerText = data.http2.sent_frames.length;
   } else {
       d.getElementById("h2-frames").innerText = "N/A";
   }

   // Cipher suites
   cipherTable = d.getElementById("cipher-suites");
   data.tls.ciphers.forEach((suite, i) => {
       cipherTable.insertRow(i+1).innerHTML = `<td>${suite}</td>`;
   });

   // tls extensions
   extTable = d.getElementById("tls-extensions");
   data.tls.extensions.forEach((ext, i) => {
       extTable.insertRow(i+1).innerHTML = `<td>${ext}</td>`;
   });

   // tls curves
   curveTable = d.getElementById("tls-curves");
   data.tls.curves.forEach((curve, i) => {
       curveTable.insertRow(i+1).innerHTML = `<td>${curve}</td>`;
   });

};

const toggleTheme = () => {
   const html = document.querySelector('html');
   const theme = html.getAttribute('data-theme');
   if (theme === 'dark') {
       html.setAttribute('data-theme', 'light');
   } else {
       html.setAttribute('data-theme', 'dark');
   }
};

const track = () => {
fetch('/api/all')
 .then((res) => res.json())
 .then((res) => {window.data = res})
 .then(() => insert(window.data));
};

const togglePadding = () => {
       const include = "Padding: <u>include</u>"
       const exclude = "Padding: <u>exclude</u>"

       let elem = document.getElementById("togglePadding");
       if (elem.innerHTML == include) {
               elem.innerHTML = exclude
                                       
               document.getElementById('ja3-hash').innerText = window.data.tls.ja3_hash;
               document.getElementById('ja3').innerText = window.data.tls.ja3;
       } else if (elem.innerHTML == exclude) {
               elem.innerHTML = include

               document.getElementById('ja3-hash').innerText = window.data.tls.ja3_hash_padding;
               document.getElementById('ja3').innerText = window.data.tls.ja3_padding;
       }
};
~~~

**Comment by 89z** [comment]
oh I see the `body` is suppose to call `track()`. That is weird. At any rate, if I manually call track, I get this:

~~~
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. 
~~~

**Comment by wwhtrbbtt** [comment]
The connection now also stays open for another 500ms after the last data frame has been sent, this is important for firefox.
Also, it now somehow works when you throttle the network speed to a slower speed artificially (or probably when your network is slow enough)

**Comment by 89z** [comment]
the page itself seems to consistently load now, but the actual data seems to get stuck on Loading

**Comment by 89z** [comment]
I think you are talking HTTP/2 language. Are you forced to use that over HTTP/1.1 for some reason? It seems you could just send a custom ALPN to force HTTP/1.1. At any rate, it seems to be working now, so much appreciated

**Comment by wwhtrbbtt** [comment]
Yes, it is needed that this server supports HTTP/2, because the main point of the project is to fingerprint TLS and HTTP/2 clients :)
