### ISSUE TITLE
Requester IP address in MongoDB

### ISSUE THREAD

**Issue by ne4u** [wwhtrbbtt/TrackMe#8]
Logging the IP & timestamp of a request in a separate mongodb object w/ a "foreign key" like reference to the fingerprint object may be helpful.

**Comment by wwhtrbbtt** [comment]
I want to stay compliant with the GDPR, so this is probably not possible under this aspect

**Comment by ne4u** [comment]
I understand the GDPR compliance requirement.  I suppose it could be a config option.

**Comment by wwhtrbbtt** [comment]
Yeah, thats true. You can make a pull request if you need the feature, but I dont really see a use for it

**Comment by wwhtrbbtt** [comment]
I added it in the newest push request
